#ifndef _MSG_ID_H_
#define _MSG_ID_H_

#define WM_ENABLE_BTN_GO (WM_USER+2000)
#define WM_FILE_LIST_START_LOAD (WM_USER+2001)
#define WM_LOADING_COMPLETE (WM_USER+2002)
#define WM_SET_VIEW_SIZE (WM_USER+2003)
#define WM_REARRANGE_TAB_SIZE (WM_USER+2004)
#define WM_EXPORT_LIST_FILE (WM_USER+2005)
#define WM_LIST_FILE_VALID (WM_USER+2006)

#define IDW_MAIN_VIEW 1
#define IDW_HEAD_BAR  2
#define IDW_BASE_BAR  3

#endif
